name = "workers-tunnel"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-02"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
USER_ID = "12345678-1234-4abc-9def-000000000000" # your uuid
PROXY_IP = "43.218.77.16:1443" # proxyip.fxxk.dedyn.io
FALLBACK_SITE = "https://httpbin.org/status/404" # https://httpbin.org/status/404
SHOW_URI = "true" # show vless uri in /UUID path
